### PR TITLE
Initial auth implementation

### PR DESCRIPTION
**Pull request by zhudotexe**
Django's first-class user support is a work of art.

To log in, ensure the correct environment variables are set (see `README.md`) and navigate to `/accounts/login`. There, you can either create an account or log in with Discord.

Eventually that page needs some styling.

This also demonstrates how to access the user object (see `user/views.py`).

### CODE REVIEW

**Review by qxzcode — APPROVED** [review]
Looks good for initial user support. Like you said, very clean with these libraries. 👍

**Comment by qxzcode** [comment]
What are the relevant account management URLs created by this pull request?

**Comment by zhudotexe** [comment]
The docs have all the relevant views: https://django-allauth.readthedocs.io/en/latest/views.html

Email verification is turned off, though.

**Review by SansPapyrus683 — APPROVED** [review]
yeah seems legit
you're planning to get the discord tokens and stuff through the allauth thing right?

**Pull request merged**
